name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        section: [1, 2]
    steps:
    - uses: jcs090218/setup-emacs@master
      with:
        version: 28.2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - uses: actions/checkout@v2

    - name: Expose section info
      run: echo "ELPA_SECTION=${{ matrix.section }}" >> $GITHUB_ENV

    - name: Build packages
      continue-on-error: true
      run: make build_packages

    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Push updated packages
      continue-on-error: true
      run: |
        git pull
        git add docs
        git commit -m "Update packages in section ${{ matrix.section }}"
        git push

    - name: Push generated badges - packages
      continue-on-error: true
      uses: jcs090218/github-push-action@master
      with:
        branch: master
        rebase: true
        retry: ${{ strategy.job-total }}
