name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: 27.2
    
    - uses: conao3/setup-cask@master
      with:
        version: 'snapshot'

    - uses: actions/checkout@v2

    - name: Build packages
      run: |
        cask install
        cask exec github-elpa update

    - name: Push to repo
      continue-on-error: true
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update pages"
        git push
