name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conao3/setup-cask@master
      with:
        version: 'snapshot'

    - uses: actions/checkout@v2

    - name: Build packages
      run: |
        cask install
        cask exec github-elpa update
        git push
