name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: 27.2

    - uses: conao3/setup-cask@master
      with:
        version: 'snapshot'

    - uses: actions/checkout@v2

    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Build packages
      run: |
        cask install
        cask exec github-elpa update -a "./docs/packages"

    - name: Generate archive.json file
      run: make generate_archive_json

    - name: Push to repo
      continue-on-error: true
      run: |
        git pull
        git add .
        git commit -m "Update archive.json"
        git push

    - name: Generate SVG badges
      run: make generate_badges

    - name: Push to repo
      continue-on-error: true
      run: |
        git pull
        git add .
        git commit -m "Update SVG badges"
        git push
