name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: 28.1

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - uses: emacs-eask/setup-eask@master
      with:
        version: '0.4.24'

    - uses: actions/checkout@v2

    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Build packages
      run: make build

    - name: Generate archive.json file
      run: make generate_archive_json

    - name: Push built packages
      continue-on-error: true
      run: |
        git pull
        git add .
        git push

    - name: Push generated archive.json
      continue-on-error: true
      run: |
        git commit -m "Update archive.json"
        git push

    - name: Generate SVG badges (system)
      run: make generate_badges_system

    - name: Push generated badges (system)
      continue-on-error: true
      run: |
        git pull
        git add .
        git commit -m "Update SVG badges - system"
        git push

    - name: Generate SVG badges (version)
      run: make generate_badges_version

    - name: Push generated badges (version)
      continue-on-error: true
      run: |
        git pull
        git add .
        git commit -m "Update SVG badges - version"
        git push

    - name: Move badges to home
      run: mv ./badges/ ~/

    - name: Checkout badges repository
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPO_BADGES }}
        persist-credentials: false
        fetch-depth: 0

    - name: Move badges to repository (Unix)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: mv -f ~/badges/* ./elpa/

    - name: Move badges to repository (Windows)
      if: matrix.os == 'windows-latest'
      run: mv -Force ~/badges/* ./elpa/
