name: Version

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REPO_BADGES: 'jcs-emacs/badges'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jcs090218/setup-emacs@master
      with:
        version: 28.1

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - uses: emacs-eask/setup-eask@master
      with:
        version: '0.4.24'

    - uses: actions/checkout@v2

    - name: Generate SVG badges (version)
      run: make generate_badges_version

    - name: Move badges to home
      run: mv ./badges/ ~/

    - name: Checkout badges repository
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPO_BADGES }}
        persist-credentials: false
        fetch-depth: 0

    - name: Move badges to repository
      run: |
        rm -rf ./elpa/*
        mv -f ~/badges/* ./elpa/

    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Commit
      continue-on-error: true
      run: |
        git pull
        git add .
        git commit -m "Update SVG badges - VERSION"

    - name: Push generated badges - VERSION
      continue-on-error: true
      uses: ad-m/github-push-action@master
      with:
        repository: ${{ env.REPO_BADGES }}
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        branch: master
